version: '3.9'
services:
  mdsim:
    image: clonardo/socketio-backend
    build:
      context: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command:
      - node
      - ./src/index.js
